[package]
name = "html5ever-stream"
version = "0.1.0"
authors = ["Ross Delinger <rossdylan@fastmail.com>"]

[dependencies]
futures = "0.1"
html5ever = "0.22"

[dev-dependencies]
hyper = "0.11"

[dev-dependencies.reqwest]
version = "0.8"
features = ["unstable"]
