[package]
name = "html5ever-stream"
version = "0.1.0"
authors = ["Ross Delinger <rossdylan@fastmail.com>"]

[dependencies]
failure = "0.1"
failure_derive = "0.1"
futures = "0.1"
html5ever = "0.22"
hyper = "0.12"
